"""praktyki_rok_akademicki

Revision ID: 4845f70310a6
Revises: 771371d4fc1e
Create Date: 2026-04-15 18:26:05.999084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4845f70310a6'
down_revision = '771371d4fc1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('praktyki', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rok_akademicki', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('praktyki', schema=None) as batch_op:
        batch_op.drop_column('rok_akademicki')

    # ### end Alembic commands ###
