"""praktyki dziennik dokumenty + pola profilu

Revision ID: 771371d4fc1e
Revises: 86a1fac081e9
Create Date: 2026-04-15 12:34:30.847220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771371d4fc1e'
down_revision = '86a1fac081e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('praktyki',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('promotor_id', sa.Integer(), nullable=True),
    sa.Column('firma_nazwa', sa.String(length=255), nullable=False),
    sa.Column('firma_adres', sa.String(length=255), nullable=True),
    sa.Column('firma_nip', sa.String(length=20), nullable=True),
    sa.Column('opiekun_zakladowy_imie_nazwisko', sa.String(length=200), nullable=True),
    sa.Column('opiekun_zakladowy_stanowisko', sa.String(length=150), nullable=True),
    sa.Column('opiekun_zakladowy_kontakt', sa.String(length=150), nullable=True),
    sa.Column('data_od', sa.Date(), nullable=True),
    sa.Column('data_do', sa.Date(), nullable=True),
    sa.Column('liczba_godzin', sa.Integer(), nullable=True),
    sa.Column('zakres_zadan', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ocena', sa.String(length=20), nullable=True),
    sa.Column('komentarz_promotora', sa.Text(), nullable=True),
    sa.Column('sprawozdanie_tresc', sa.Text(), nullable=True),
    sa.Column('sprawozdanie_wnioski', sa.Text(), nullable=True),
    sa.Column('ankieta_atmosfera', sa.Integer(), nullable=True),
    sa.Column('ankieta_organizacja', sa.Integer(), nullable=True),
    sa.Column('ankieta_wiedza', sa.Integer(), nullable=True),
    sa.Column('ankieta_komentarz', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['promotor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('praktyki', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_praktyki_promotor_id'), ['promotor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_praktyki_student_id'), ['student_id'], unique=False)

    op.create_table('dokumenty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('praktyka_id', sa.Integer(), nullable=False),
    sa.Column('typ', sa.String(length=30), nullable=False),
    sa.Column('nazwa_oryginalna', sa.String(length=255), nullable=False),
    sa.Column('nazwa_pliku', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('rozmiar', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['praktyka_id'], ['praktyki.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dokumenty', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dokumenty_praktyka_id'), ['praktyka_id'], unique=False)

    op.create_table('dziennik_wpisy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('praktyka_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('godz_od', sa.Time(), nullable=True),
    sa.Column('godz_do', sa.Time(), nullable=True),
    sa.Column('opis', sa.Text(), nullable=False),
    sa.Column('efekty', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['praktyka_id'], ['praktyki.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dziennik_wpisy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dziennik_wpisy_praktyka_id'), ['praktyka_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rok_studiow', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('semestr', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('telefon', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('adres', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('adres')
        batch_op.drop_column('telefon')
        batch_op.drop_column('semestr')
        batch_op.drop_column('rok_studiow')

    with op.batch_alter_table('dziennik_wpisy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dziennik_wpisy_praktyka_id'))

    op.drop_table('dziennik_wpisy')
    with op.batch_alter_table('dokumenty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dokumenty_praktyka_id'))

    op.drop_table('dokumenty')
    with op.batch_alter_table('praktyki', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_praktyki_student_id'))
        batch_op.drop_index(batch_op.f('ix_praktyki_promotor_id'))

    op.drop_table('praktyki')
    # ### end Alembic commands ###
