"""initial users table

Revision ID: 86a1fac081e9
Revises: 
Create Date: 2026-04-15 12:16:13.201584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86a1fac081e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ms_oid', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('imie', sa.String(length=100), nullable=True),
    sa.Column('nazwisko', sa.String(length=100), nullable=True),
    sa.Column('nr_albumu', sa.String(length=20), nullable=True),
    sa.Column('kierunek', sa.String(length=100), nullable=True),
    sa.Column('rola', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_ms_oid'), ['ms_oid'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_nr_albumu'), ['nr_albumu'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_nr_albumu'))
        batch_op.drop_index(batch_op.f('ix_users_ms_oid'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
